spring.application.name=academia

spring.datasource.url=jdbc:sqlserver//localhost:1433;databaseName=academia;encrypt=true;trustServerCertificate=true

spring.profiles.active=sqlserver

spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

loggin.level.root=INFO
loggin.level.com.facens.academia=DEBUG